"""

Python Generated by the OSKAR Compiler v2.3 at
2017-06-12 09:23:20.0920115 Eastern Daylight Time

Compiler written by Bryce Summers
Please see https://github.com/Bryce-Summers/OSKAR

"""

from pythonGenerator import *

# Global Variables

scene = Scene()

# 0 functions parsed.

# Picture definition for floor
scene.newPicture("floor")
scene.iterations("i", "0", "1")
scene.scaling("2", "2", ".02")
scene.translation("-.5", "-.5", "-.05")
scene.basis("cube")

# Picture definition for cosine
scene.newPicture("cosine")
scene.iterations("i", "0", "80")
scene.scaling(".0125", ".02", ".02")
scene.scaling(".5", "4", "5")
scene.translation("i", "cos ( ( i * 360 ) + ( Global_t * 360 ) )", ".05")
scene.scaling("1", ".5", "1")
scene.translation("0", ".5", "0")
scene.basis("cube")


# Top level picture definition.
scene.newDrawCommand("draw")
scene.iterations("i", "0", "1")
scene.basis("floor")
scene.basis("cosine")


# Generate Code in a Render Language
scene.generateCode()
