"""

Python Generated by the OSKAR Compiler at
2017-02-17 16:49:12.4450676 Eastern Standard Time

Compiler written by Bryce Summers
Please see https://github.com/Bryce-Summers/OSKAR

"""

from pythonGenerator import *

# Global Variables

scene = Scene()

# Picture definition for floor
scene.newPicture("floor")
scene.iterations("i", 0, 1)
scene.scaling("2", "2", ".02")
scene.translation("-.5", "-.5", "-.05")
scene.basis("cube")

# Picture definition for row
scene.newPicture("row")
scene.iterations("i", 0, 20)
scene.translation("-.5", "-.5", "-.5")
scene.scaling(".1", ".025", ".1")
scene.rotation("0", "i * 9 ) + Global_t * 360 )", "0")
scene.translation("0", "i * .05", "0")
scene.translation("0", "0", ".05")
scene.basis("cube")

# Picture definition for grid
scene.newPicture("grid")
scene.iterations("j", 0, 7)
scene.translation("j * .11", "0", "0")
scene.basis("row")

# Picture definition for wheel
scene.newPicture("wheel")
scene.iterations("k", 0, 10)
scene.translation("-1", "0", "-.05")
scene.rotation("0", "k * 20", "0")
scene.translation(".5", "0", ".05")
scene.basis("grid")

# Picture definition for wheel_0
scene.newPicture("wheel_0")
scene.iterations("i", 0, 20)
scene.translation("-.5", "-.5", "-.5")
scene.scaling(".1", ".025", ".1")
scene.rotation("0", "i * 9 ) + Global_t * 360 )", "0")
scene.translation("0", "i * .05", "0")
scene.translation("0", "0", ".05")
scene.basis("cube")

# Picture definition for wheel_1
scene.newPicture("wheel_1")
scene.iterations("j", 0, 7)
scene.translation("j * .11", "0", "0")
scene.basis("wheel_0")

# Picture definition for wheel
scene.newPicture("wheel")
scene.iterations("k", 0, 10)
scene.translation("-1", "0", "-.05")
scene.rotation("0", "k * 20", "0")
scene.translation(".5", "0", ".05")
scene.basis("wheel_1")


#Top level picture definition.
scene.newDrawCommand("draw")
scene.iterations("i", 0, 1)
scene.basis("floor")
scene.basis("row")

#Top level picture definition.
scene.newDrawCommand("draw")
scene.iterations("i", 0, 1)
scene.basis("floor")
scene.basis("grid")

#Top level picture definition.
scene.newDrawCommand("draw")
scene.iterations("i", 0, 1)
scene.basis("floor")
scene.basis("wheel")

#Top level picture definition.
scene.newDrawCommand("draw")
scene.iterations("i", 0, 150)
scene.basis("floor")
scene.basis("wheel")

#Top level picture definition.
scene.newDrawCommand("draw")
scene.iterations("i", 0, 150)
scene.basis("floor")
scene.basis("wheel")


#Generate Code in a Render Language
scene.generateCode()
