"""

Python Generated by the OSKAR Compiler v2.3 at
2017-06-12 09:24:56.0774503 Eastern Daylight Time

Compiler written by Bryce Summers
Please see https://github.com/Bryce-Summers/OSKAR

"""

from pythonGenerator import *

# Global Variables

scene = Scene()

p = scene.newFunction("myTY1")
p.addArgument("x")
p.addArgument("time")
p.addExpression("cos((x*360)+(time*360))")
p.scalar_type()

# 1 functions parsed.

# Picture definition for floor
scene.newPicture("floor")
scene.iterations("i", "0", "1")
scene.scaling("2", "2", ".02")
scene.translation("-.5", "-.5", "-.05")
scene.basis("cube")

# Picture definition for cosine
scene.newPicture("cosine")
scene.iterations("i", "0", "80")
scene.scaling(".0125", ".02", ".02")
scene.scaling(".5", "4", "5")
scene.translation("i", "myTY1 ( i , Global_t )", ".05")
scene.scaling("1", ".5", "1")
scene.translation("0", ".5", "0")
scene.basis("cube")


# Top level picture definition.
scene.newDrawCommand("draw")
scene.iterations("i", "0", "400")
scene.basis("floor")
scene.basis("cosine")


# Generate Code in a Render Language
scene.generateCode()
