"""

Python Generated by OSKAR Compiler

Compiler written by Bryce Summers

Please see https://github.com/Bryce-Summers/OSKAR

"""

#Global Variables
$t = 0


def floor():
   for i in range(0, 1):
      pushState()
      Scale(2, 2, .02)
      Translation(-.5, -.5, -.05)
      
      cube()
      popState()

def row():
   for i in range(0, 20):
      pushState()
      Translation(-.5, -.5, -.5)
      Scale(.1, .025, .1)
      Rotate(0, ( i * 9 ) + ( $t * 360 ), 0)
      Translation(0, i * .05, 0)
      Translation(0, 0, .05)
      
      cube()
      popState()

def grid():
   for j in range(0, 7):
      pushState()
      Translation(j * .11, 0, 0)
      
      row()
      popState()

def wheel():
   for k in range(0, 10):
      pushState()
      Translation(-1, 0, -.05)
      Scale(0, k * 20, 0)
      Translation(.5, 0, .05)
      
      grid()
      popState()

def wheel_0():
   for i in range(0, 20):
      pushState()
      Translation(-.5, -.5, -.5)
      Scale(.1, .025, .1)
      Rotate(0, ( i * 9 ) + ( $t * 360 ), 0)
      Translation(0, i * .05, 0)
      Translation(0, 0, .05)
      
      cube()
      popState()

def wheel_1():
   for j in range(0, 7):
      pushState()
      Translation(j * .11, 0, 0)
      
      wheel_0()
      popState()

def wheel():
   for k in range(0, 10):
      pushState()
      Translation(-1, 0, -.05)
      Scale(0, k * 20, 0)
      Translation(.5, 0, .05)
      
      wheel_1()
      popState()

DrawCommand
DrawCommand
DrawCommand
DrawCommand
DrawCommand
